name: 'Build LaTex Document'
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic resume.tex
      - name: Upload pdf
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
      - name: copy to site
        run: cp resume.pdf site/resume.pdf
      - uses: stefanzweifel/git-auto-commit-action@v5
